version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: kuldeep400/shreyansh:2008
    container_name: tomcat-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=studentapp
      - DB_USER=root
      - DB_PASSWORD=root
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

